# Generated by Django 6.0.5 on 2026-07-16 13:33

import django.db.models.deletion
import news.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0004_task_reject_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('category', models.CharField(choices=[('notice', '社团公告'), ('recap', '活动回顾'), ('work', '作品展示'), ('inform', '通知')], default='notice', max_length=20, verbose_name='分类')),
                ('summary', models.CharField(blank=True, default='', max_length=280, verbose_name='摘要')),
                ('content', models.TextField(blank=True, default='', verbose_name='正文（HTML）')),
                ('cover_image', models.ImageField(blank=True, upload_to=news.models.cover_upload_path, verbose_name='封面图')),
                ('featured', models.BooleanField(default=False, verbose_name='头条')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('is_published', models.BooleanField(default=True, verbose_name='已发布')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('tags', models.ManyToManyField(blank=True, related_name='news', to='tasks.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
