# Generated by Django 6.0.5 on 2026-07-20 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_create_info_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='阅读人数'),
        ),
        migrations.CreateModel(
            name='NewsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_key', models.CharField(max_length=80, verbose_name='读者标识')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='阅读时间')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='news.news', verbose_name='新闻')),
            ],
            options={
                'verbose_name': '阅读记录',
                'verbose_name_plural': '阅读记录',
                'unique_together': {('news', 'reader_key')},
            },
        ),
    ]
