# Generated by Django 6.0.5 on 2026-09-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at', '-created_at'], 'permissions': [('manage_news', '可管理新闻')], 'verbose_name': '新闻', 'verbose_name_plural': '新闻'},
        ),
    ]
