# Generated by Django 6.0.5 on 2026-09-24 11:22

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cover_thumbnail',
            field=models.ImageField(blank=True, upload_to=news.models.cover_thumbnail_path, verbose_name='封面缩略图'),
        ),
    ]
