# Generated by Django 6.0.5 on 2026-09-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_cover_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='draft_content',
            field=models.TextField(blank=True, default='', verbose_name='草稿正文（HTML）'),
        ),
        migrations.AddField(
            model_name='news',
            name='draft_saved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='草稿保存时间'),
        ),
        migrations.AddField(
            model_name='news',
            name='draft_summary',
            field=models.CharField(blank=True, default='', max_length=280, verbose_name='草稿摘要'),
        ),
        migrations.AddField(
            model_name='news',
            name='draft_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='草稿标题'),
        ),
    ]
