# Generated by Django 6.0.5 on 2026-08-05 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deliberation', '众议'), ('collection', '征集')], max_length=12, verbose_name='类型')),
                ('status', models.CharField(choices=[('open', '进行中'), ('closed', '已结束'), ('collecting', '收件中'), ('reviewing', '复审中'), ('archived', '已归档')], max_length=12, verbose_name='状态')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('body', models.TextField(blank=True, default='', verbose_name='正文（HTML）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'ordering': ['-created_at'],
            },
        ),
    ]
