# Generated by Django 6.0.5 on 2026-08-05 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='截止时间'),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_choices_per_voter',
            field=models.PositiveIntegerField(default=1, verbose_name='每人最多选几项'),
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='activities.activity', verbose_name='活动')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_ballots', to=settings.AUTH_USER_MODEL, verbose_name='投票人')),
            ],
            options={
                'verbose_name': '选票',
                'verbose_name_plural': '选票',
                'ordering': ['created_at'],
                'unique_together': {('activity', 'voter')},
            },
        ),
        migrations.CreateModel(
            name='VoteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='选项文本')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='activities.activity', verbose_name='活动')),
            ],
            options={
                'verbose_name': '投票选项',
                'verbose_name_plural': '投票选项',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BallotSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='activities.ballot', verbose_name='选票')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='activities.voteoption', verbose_name='选项')),
            ],
            options={
                'verbose_name': '投票选择',
                'verbose_name_plural': '投票选择',
                'unique_together': {('ballot', 'option')},
            },
        ),
    ]
