# Generated by Django 6.0.5 on 2026-08-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_end_at_activity_max_choices_per_voter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_secret_ballot',
            field=models.BooleanField(default=False, verbose_name='秘密投票'),
        ),
    ]
