# Generated by Django 6.0.5 on 2026-08-05 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_is_secret_ballot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='allowed_extensions',
            field=models.TextField(blank=True, default='', verbose_name='允许后缀（逗号分隔）'),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_file_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='单文件大小上限（字节）'),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_files_per_submission',
            field=models.PositiveIntegerField(default=5, verbose_name='单作品文件数上限'),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_submissions',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='最大征集数量'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(choices=[('pending', '待复审'), ('accepted', '录用'), ('rejected', '退稿')], default='pending', max_length=10, verbose_name='复审状态')),
                ('review_comment', models.TextField(blank=True, default='', verbose_name='复审评语')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复审时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='activities.activity', verbose_name='活动')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL, verbose_name='复审人')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_submissions', to=settings.AUTH_USER_MODEL, verbose_name='提交者')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
                'ordering': ['created_at'],
                'unique_together': {('activity', 'submitter')},
            },
        ),
    ]
