# Generated by Django 6.0.5 on 2026-08-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_allowed_extensions_activity_max_file_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'permissions': [('review_collection', '可复审征集作品')], 'verbose_name': '活动', 'verbose_name_plural': '活动'},
        ),
    ]
