# Generated by Django 6.0.5 on 2026-08-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_grant_review_collection_to_president'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('scheduled', '待开始'), ('open', '进行中'), ('closed', '已结束'), ('collecting', '收件中'), ('reviewing', '复审中'), ('archived', '已归档')], max_length=12, verbose_name='状态'),
        ),
    ]
