# Generated by Django 6.0.5 on 2026-08-07 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_activity_start_at_alter_activity_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('deliberation', '众议'), ('collection', '征集'), ('exhibition', '展示')], max_length=12, verbose_name='类型'),
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='标题')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to='activities.activity', verbose_name='所属展示')),
                ('source_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_exhibits', to='activities.submission', verbose_name='来源作品')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_exhibits', to=settings.AUTH_USER_MODEL, verbose_name='提交者')),
            ],
            options={
                'verbose_name': '展品',
                'verbose_name_plural': '展品',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('like', '赞'), ('dislike', '踩')], max_length=8, verbose_name='选择')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='activities.exhibit', verbose_name='展品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibit_ratings', to=settings.AUTH_USER_MODEL, verbose_name='评分人')),
            ],
            options={
                'verbose_name': '展品评分',
                'verbose_name_plural': '展品评分',
                'ordering': ['created_at'],
                'unique_together': {('exhibit', 'user')},
            },
        ),
    ]
