# Generated by Django 6.0.5 on 2026-08-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_activity_type_exhibit_exhibitrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='review_enabled',
            field=models.BooleanField(default=True, verbose_name='需要复审'),
        ),
    ]
