# Generated by Django 6.0.5 on 2026-08-10 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_activity_review_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='source_submission',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='submitter',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='vote_option',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibit', to='activities.voteoption', verbose_name='对应投票选项'),
        ),
    ]
