# Generated by Django 6.0.5 on 2026-08-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_remove_exhibit_source_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='voting_enabled',
            field=models.BooleanField(default=False, verbose_name='启用投票'),
        ),
    ]
