# Generated by Django 6.0.5

import activities.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0011_activity_voting_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="type",
            field=models.CharField(
                choices=[
                    ("deliberation", "众议"),
                    ("collection", "征集"),
                    ("exhibition", "展示"),
                    ("survey", "调研"),
                ],
                max_length=12,
                verbose_name="类型",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="audience",
            field=models.CharField(
                choices=[("public", "公开"), ("members", "仅成员")],
                default="members",
                max_length=8,
                verbose_name="受众",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="schema",
            field=models.JSONField(
                default=activities.models.default_survey_schema,
                verbose_name="问卷 Schema",
            ),
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("answers", models.JSONField(default=dict, verbose_name="作答")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_responses",
                        to="activities.activity",
                        verbose_name="活动",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_responses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作答者",
                    ),
                ),
            ],
            options={
                "verbose_name": "调研作答",
                "verbose_name_plural": "调研作答",
                "ordering": ["-submitted_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("activity", "user"),
                        name="unique_survey_response_per_user",
                    ),
                ],
            },
        ),
    ]
