# Generated by Django 6.0.5

import activities.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_surveys_and_join(apps, schema_editor):
    Activity = apps.get_model("activities", "Activity")
    Questionnaire = apps.get_model("activities", "Questionnaire")
    QuestionnaireResponse = apps.get_model("activities", "QuestionnaireResponse")
    SurveyResponse = apps.get_model("activities", "SurveyResponse")
    JoinQuestionnaire = apps.get_model("recruitment", "JoinQuestionnaire")
    JoinResponse = apps.get_model("recruitment", "JoinResponse")

    for activity in Activity.objects.filter(type="survey"):
        q = Questionnaire.objects.create(kind="survey", schema=activity.schema or {"title": "", "pages": [{"name": "page1", "elements": []}]})
        Activity.objects.filter(pk=activity.pk).update(questionnaire=q)
        for row in SurveyResponse.objects.filter(activity_id=activity.pk):
            copied = QuestionnaireResponse.objects.create(
                questionnaire=q,
                user=row.user,
                device_id="",
                answers=row.answers or {},
            )
            QuestionnaireResponse.objects.filter(pk=copied.pk).update(submitted_at=row.submitted_at)

    join = JoinQuestionnaire.objects.filter(pk=1).first()
    join_q, _ = Questionnaire.objects.get_or_create(
        kind="join",
        defaults={"schema": (join.schema if join else None) or activities.models.default_join_schema()},
    )
    if join is not None and join.schema:
        Questionnaire.objects.filter(pk=join_q.pk).update(schema=join.schema)
    if not QuestionnaireResponse.objects.filter(questionnaire=join_q).exists():
            for row in JoinResponse.objects.all():
                copied = QuestionnaireResponse.objects.create(
                    questionnaire=join_q,
                    user=row.user,
                    device_id="",
                    answers=row.answers or {},
                )
                QuestionnaireResponse.objects.filter(pk=copied.pk).update(submitted_at=row.submitted_at)


def uncopy_surveys_and_join(apps, schema_editor):
    Activity = apps.get_model("activities", "Activity")
    Questionnaire = apps.get_model("activities", "Questionnaire")
    SurveyResponse = apps.get_model("activities", "SurveyResponse")
    JoinQuestionnaire = apps.get_model("recruitment", "JoinQuestionnaire")
    JoinResponse = apps.get_model("recruitment", "JoinResponse")
    QuestionnaireResponse = apps.get_model("activities", "QuestionnaireResponse")

    for q in Questionnaire.objects.filter(kind="survey"):
        activity = Activity.objects.filter(questionnaire_id=q.pk).first()
        if activity is None:
            continue
        Activity.objects.filter(pk=activity.pk).update(schema=q.schema)
        for row in QuestionnaireResponse.objects.filter(questionnaire=q):
            SurveyResponse.objects.create(
                activity=activity,
                user=row.user,
                answers=row.answers or {},
                submitted_at=row.submitted_at,
            )

    join_q = Questionnaire.objects.filter(kind="join").first()
    if join_q is not None:
        jq, _ = JoinQuestionnaire.objects.get_or_create(pk=1, defaults={"schema": join_q.schema})
        JoinQuestionnaire.objects.filter(pk=jq.pk).update(schema=join_q.schema)
        if not JoinResponse.objects.exists():
            for row in QuestionnaireResponse.objects.filter(questionnaire=join_q):
                JoinResponse.objects.create(
                    user=row.user,
                    answers=row.answers or {},
                    submitted_at=row.submitted_at,
                )

    Questionnaire.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0012_activity_survey_type"),
        ("recruitment", "0002_seed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("survey", "调研"), ("join", "自我介绍")],
                        max_length=12,
                        verbose_name="用途",
                    ),
                ),
                ("schema", models.JSONField(default=activities.models.default_survey_schema, verbose_name="问卷 Schema")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "问卷",
                "verbose_name_plural": "问卷",
                "ordering": ["-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "join")),
                        fields=("kind",),
                        name="unique_join_questionnaire",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QuestionnaireResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_id", models.CharField(blank=True, default="", max_length=36, verbose_name="设备标识")),
                ("answers", models.JSONField(default=dict, verbose_name="作答")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="activities.questionnaire",
                        verbose_name="问卷",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questionnaire_responses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作答者",
                    ),
                ),
            ],
            options={
                "verbose_name": "问卷结果",
                "verbose_name_plural": "问卷结果",
                "ordering": ["-submitted_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("questionnaire", "user"),
                        name="unique_questionnaire_response_per_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", True), models.Q(("device_id", ""), _negated=True)),
                        fields=("questionnaire", "device_id"),
                        name="unique_questionnaire_response_per_device",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="questionnaire",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="survey_activity",
                to="activities.questionnaire",
                verbose_name="问卷",
            ),
        ),
        migrations.RunPython(copy_surveys_and_join, uncopy_surveys_and_join),
        migrations.RemoveField(
            model_name="activity",
            name="schema",
        ),
        migrations.DeleteModel(
            name="SurveyResponse",
        ),
    ]
