# Generated by Django 6.0.5 on 2026-09-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_questionnaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'permissions': [('review_collection', '可复审征集作品'), ('manage_activity', '可管理任意活动')], 'verbose_name': '活动', 'verbose_name_plural': '活动'},
        ),
    ]
