# Generated by Django 6.0.5 on 2026-09-24 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_alter_activity_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='device_id',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='设备标识'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='voter_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='游客IP'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_ballots', to=settings.AUTH_USER_MODEL, verbose_name='投票人'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.UniqueConstraint(condition=models.Q(('voter__isnull', True), models.Q(('device_id', ''), _negated=True)), fields=('activity', 'device_id'), name='unique_ballot_per_device'),
        ),
    ]
