# Generated by Django 6.0.5 on 2026-09-24 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_ballot_device_id_ballot_voter_ip_alter_ballot_voter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questionnaireresponse',
            name='unique_questionnaire_response_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='questionnaireresponse',
            name='unique_questionnaire_response_per_device',
        ),
        migrations.AddIndex(
            model_name='questionnaireresponse',
            index=models.Index(fields=['questionnaire', 'user'], name='qresp_questionnaire_user_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaireresponse',
            index=models.Index(fields=['questionnaire', 'device_id'], name='qresp_questionnaire_dev_idx'),
        ),
    ]
