# Generated by Django 6.0.5

from django.conf import settings
from django.db import migrations, models
import recruitment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruitmentNotice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(blank=True, default="", verbose_name="公告正文（HTML）")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "招生公告", "verbose_name_plural": "招生公告"},
        ),
        migrations.CreateModel(
            name="JoinQuestionnaire",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("schema", models.JSONField(default=recruitment.models.default_schema, verbose_name="问卷 Schema")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "自我介绍问卷", "verbose_name_plural": "自我介绍问卷"},
        ),
        migrations.CreateModel(
            name="JoinResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("answers", models.JSONField(default=dict, verbose_name="作答")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET_NULL,
                        related_name="join_responses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作答者",
                    ),
                ),
            ],
            options={"ordering": ["-submitted_at"], "verbose_name": "加入作答", "verbose_name_plural": "加入作答"},
        ),
    ]
