# Generated by Django 6.0.5 on 2026-08-25 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='auto_update_enabled',
            field=models.BooleanField(default=True, help_text='关闭后守护进程跳过下载与应用。', verbose_name='开启自动更新'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='update_apply_cutoff_minutes_before_end',
            field=models.PositiveIntegerField(default=30, help_text='窗口结束前 N 分钟起不再开始应用更新。', verbose_name='窗口结束前截止分钟'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='update_db_backup_keep',
            field=models.PositiveIntegerField(default=5, verbose_name='保留数据库快照份数'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='update_poll_interval_seconds',
            field=models.PositiveIntegerField(default=900, verbose_name='轮询间隔（秒）'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='update_release_keep',
            field=models.PositiveIntegerField(default=3, verbose_name='保留发行包份数'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='update_timezone',
            field=models.CharField(default='Asia/Shanghai', help_text='IANA 时区名；不用 Django TIME_ZONE。', max_length=63, verbose_name='更新时区'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='update_window_end_hour',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='窗口结束时刻（时）'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='update_window_start_hour',
            field=models.PositiveSmallIntegerField(default=1, help_text='应用窗口为 [开始, 结束) 的整点小时，时区见「更新时区」。', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='窗口开始时刻（时）'),
        ),
    ]
