# Generated by Django 6.0.5 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_sitesettings_auto_update_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="content_review_enabled",
            field=models.BooleanField(
                default=True,
                help_text="关闭后新建新闻、活动、教程直接通过，不进待审队列；已有待审条目不会批量通过。",
                verbose_name="开启内容审核",
            ),
        ),
    ]
