# Generated by Django 6.0.5 on 2026-08-27 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_sitesettings_content_review_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='comment_max_depth',
            field=models.PositiveSmallIntegerField(default=8, help_text='1 表示仅允许根评论；超过则拒绝，不改挂。', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)], verbose_name='评论最大嵌套深度'),
        ),
    ]
