# Generated by Django 6.0.5

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_sitesettings_comment_max_depth"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="login_per_ip_per_hour",
            field=models.PositiveIntegerField(
                default=30,
                help_text="门户登录与 Django admin 登录共用。只计失败，成功登录不占额度。",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="每 IP 每小时登录失败次数",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="login_per_username_per_hour",
            field=models.PositiveIntegerField(
                default=10,
                help_text="按用户名或邮箱计，防针对单一账号的撞库。",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="每用户名每小时登录失败次数",
            ),
        ),
    ]
