# Generated by Django 6.0.5

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_sitesettings_login_throttle"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="reports_per_user_per_day",
            field=models.PositiveIntegerField(
                default=10,
                help_text="已验证成员提交举报的日上限。",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="每用户每日举报次数",
            ),
        ),
    ]
