# Generated by Django 6.0.5 on 2026-09-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_sitesettings_reports_per_user_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='comments_enabled',
            field=models.BooleanField(default=True, help_text='关闭后前端不再显示评论区，且无法发表新评论；已有评论保留。', verbose_name='启用评论区'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dms_enabled',
            field=models.BooleanField(default=True, help_text='关闭后前端不再显示私信入口，且无法发起或发送私信；已有会话保留。', verbose_name='启用私信'),
        ),
    ]
