# Generated by Django 6.0.5 on 2026-09-26 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_sitesettings_comments_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='authcode_redeem_per_user_per_hour',
            field=models.PositiveIntegerField(default=10, help_text='认证码兑换只计失败；成功兑换不占额度。', validators=[django.core.validators.MinValueValidator(1)], verbose_name='每账号每小时认证码兑换失败次数'),
        ),
    ]
