# Generated by Django 6.0.5 on 2026-08-01 14:25

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_default_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=True, verbose_name='邮箱已验证'),
        ),
        migrations.AddField(
            model_name='profile',
            name='identity',
            field=models.CharField(blank=True, choices=[('student', '在校生'), ('external', '外校生'), ('graduate', '毕业生')], max_length=10, verbose_name='身份'),
        ),
        migrations.AddField(
            model_name='profile',
            name='identity_verified',
            field=models.BooleanField(default=True, verbose_name='身份已审核'),
        ),
        migrations.AddField(
            model_name='profile',
            name='real_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='真实姓名'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_profiles', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.CreateModel(
            name='IdentityProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(storage=accounts.models.private_media_storage, upload_to=accounts.models.identity_proof_upload_path, verbose_name='证明材料')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_proofs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '身份证明',
                'verbose_name_plural': '身份证明',
                'ordering': ['-uploaded_at'],
                'permissions': [('can_review_identity', '可以审核身份证明材料')],
            },
        ),
    ]
