# Generated by Django 6.0.5 on 2026-08-04 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forward_default_trust(apps, schema_editor):
    """存量账号默认信任（ADR-0006 决策 13）：任一旧布尔为真（或无 profile）→ 造 manual 通道 approved 行。

    在删除 Profile 四个旧字段**之前**运行，以便读取旧 ``identity_verified`` / ``email_verified``
    判定信任态，并继承旧 ``verified_at`` / ``verified_by``。无存量用户时为 no-op（安全网）。
    迁移期历史模型不带模型类常量，故通道 / 状态用字面量。
    """
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("accounts", "Profile")
    Verification = apps.get_model("accounts", "Verification")
    for user in User.objects.all():
        profile = Profile.objects.filter(user=user).first()
        # 与旧 _email_verified / IsIdentityVerified 一致：无 profile（信任）或任一布尔为真 → 信任。
        trusted = profile is None or profile.identity_verified or profile.email_verified
        if not trusted:
            continue
        Verification.objects.get_or_create(
            user=user,
            channel="manual",
            defaults={
                "status": "approved",
                "identifier": "",
                "verified_at": getattr(profile, "verified_at", None) if profile else None,
                "verified_by_id": getattr(profile, "verified_by_id", None) if profile else None,
            },
        )


def reverse_default_trust(apps, schema_editor):
    """回滚：删 forward 造的 manual-approved 信任行（紧随其后 CreateModel 反向 drop 整表）。"""
    Verification = apps.get_model("accounts", "Verification")
    Verification.objects.filter(channel="manual", status="approved").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_email_verified_profile_identity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1) 先建 Verification 表（数据迁移要用）。
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', '邮箱'), ('manual', '人工审批')], max_length=20, verbose_name='通道')),
                ('status', models.CharField(choices=[('pending', '待验证'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=10, verbose_name='状态')),
                ('identifier', models.CharField(blank=True, default='', max_length=254, verbose_name='通道标识')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='通过时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '验证通道',
                'verbose_name_plural': '验证通道',
                'ordering': ['user', 'channel'],
                'indexes': [models.Index(fields=['user', 'status'], name='accounts_ve_user_id_b1d249_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'channel'), name='unique_user_channel')],
            },
        ),
        # 2) 默认信任：在读旧字段之前给存量账号造 approved 行。
        migrations.RunPython(forward_default_trust, reverse_default_trust),
        # 3) 删 Profile 四个旧字段（单一事实源 = Verification）。
        migrations.RemoveField(
            model_name='profile',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='identity_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verified_by',
        ),
    ]
