# Generated by Django 6.0.5 on 2026-08-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='identity',
            field=models.CharField(blank=True, choices=[('student', '在校生'), ('external', '外校生'), ('graduate', '毕业生'), ('parent', '家长'), ('teacher', '教师')], max_length=10, verbose_name='身份'),
        ),
    ]
