# Generated by Django 6.0.5 on 2026-08-27

from django.db import migrations, models
from django.db.models import Q
from django.utils import timezone


def grant_appointment(apps, schema_editor):
    """存量管理员 / 超级管理员补后台委任通道（ADR-0013）。"""
    User = apps.get_model("auth", "User")
    Verification = apps.get_model("accounts", "Verification")
    now = timezone.now()
    for user in User.objects.filter(Q(is_staff=True) | Q(is_superuser=True)):
        Verification.objects.get_or_create(
            user=user,
            channel="appointment",
            defaults={
                "status": "approved",
                "identifier": "superuser" if user.is_superuser else "staff",
                "verified_at": now,
            },
        )


def revoke_appointment(apps, schema_editor):
    Verification = apps.get_model("accounts", "Verification")
    Verification.objects.filter(channel="appointment").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_grant_review_identity_to_president"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verification",
            name="channel",
            field=models.CharField(
                choices=[
                    ("appointment", "后台委任"),
                    ("email", "邮箱"),
                    ("manual", "人工审批"),
                ],
                max_length=20,
                verbose_name="通道",
            ),
        ),
        migrations.RunPython(grant_appointment, revoke_appointment),
    ]
