# Generated by Django 6.0.5 on 2026-08-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_appointment_verification_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notify_comment',
            field=models.BooleanField(default=False, verbose_name='邮件转发评论通知'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_notify_discipline',
            field=models.BooleanField(default=False, verbose_name='邮件转发纪律通知'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_notify_review',
            field=models.BooleanField(default=False, verbose_name='邮件转发审核通知'),
        ),
    ]
