# Generated by Django 6.0.5 on 2026-09-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_grant_normalized_perms'),
        # 先由通知订阅数据迁移（messaging 0006）读取旧字段建好订阅行，之后才允许删字段。
        ('messaging', '0006_migrate_email_prefs_to_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_notify_comment',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_notify_discipline',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_notify_review',
        ),
    ]
