# Generated by Django 6.0.5 on 2026-09-26 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_profile_email_notify_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='channel',
            field=models.CharField(choices=[('appointment', '后台委任'), ('email', '邮箱'), ('manual', '人工审批'), ('authcode', '认证码')], max_length=20, verbose_name='通道'),
        ),
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='认证码')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('expires_at', models.DateTimeField(verbose_name='有效期至')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='可用次数')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='已用次数')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='吊销时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authcodes_created', to=settings.AUTH_USER_MODEL, verbose_name='生成人')),
            ],
            options={
                'verbose_name': '认证码',
                'verbose_name_plural': '认证码',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthCodeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='兑换时间')),
                ('authcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='accounts.authcode', verbose_name='认证码')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authcode_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '认证码兑换记录',
                'verbose_name_plural': '认证码兑换记录',
                'ordering': ['-redeemed_at'],
                'constraints': [models.UniqueConstraint(fields=('user',), name='unique_authcode_per_user')],
            },
        ),
    ]
