# Generated by Django 6.0.5 on 2026-07-05 15:53

import django.db.models.deletion
import proposals.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_type', models.CharField(choices=[('activity', '活动申报'), ('feedback', '意见反馈')], max_length=10, verbose_name='类型')),
                ('status', models.CharField(choices=[('voting', '投票中'), ('pending_approval', '待社长审批'), ('returned', '已打回'), ('approved', '已通过'), ('rejected', '已拒绝'), ('withdrawn', '已撤回')], default='pending_approval', max_length=20, verbose_name='状态')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='详细说明')),
                ('activity_type', models.CharField(blank=True, choices=[('competition', '比赛'), ('training', '培训'), ('project', '项目'), ('sharing', '分享'), ('event', '活动')], default='', max_length=20, verbose_name='活动类型')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='拟办日期')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='地点')),
                ('expected_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='预计人数')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预算')),
                ('feedback_category', models.CharField(blank=True, choices=[('suggestion', '建议'), ('complaint', '投诉'), ('report', '举报'), ('other', '其他')], default='', max_length=20, verbose_name='反馈类别')),
                ('contact', models.CharField(blank=True, default='', max_length=100, verbose_name='联系方式（选填）')),
                ('voting_end_at', models.DateTimeField(blank=True, null=True, verbose_name='投票截止时间')),
                ('reject_reason', models.TextField(blank=True, default='', verbose_name='打回/拒绝理由')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='通过时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proposals', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_proposals', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '申报',
                'verbose_name_plural': '申报',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=proposals.models.proposal_attachment_upload_path, verbose_name='文件')),
                ('file_type', models.CharField(choices=[('image', '图片'), ('video', '视频'), ('document', '文档'), ('archive', '压缩包'), ('other', '其他')], max_length=20, verbose_name='文件类型')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='proposals.proposal', verbose_name='申报')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_proposal_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '申报附件',
                'verbose_name_plural': '申报附件',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_choice', models.CharField(choices=[('approve', '赞成'), ('oppose', '反对'), ('abstain', '弃权')], max_length=10, verbose_name='选项')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='proposals.proposal', verbose_name='申报')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_votes', to=settings.AUTH_USER_MODEL, verbose_name='投票人')),
            ],
            options={
                'verbose_name': '投票',
                'verbose_name_plural': '投票',
                'ordering': ['created_at'],
                'unique_together': {('proposal', 'voter')},
            },
        ),
    ]
