# Generated by Django 6.0.5 on 2026-07-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-created_at'], 'permissions': [('approve_proposal', '可审批申报'), ('view_feedback', '可查看意见反馈/举报')], 'verbose_name': '申报', 'verbose_name_plural': '申报'},
        ),
    ]
