# Generated by Django 6.0.5 on 2026-07-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProposalAttachment',
        ),
    ]
