# Generated by Django 6.0.5 on 2026-08-05 15:47

from django.db import migrations, models


def delete_activity_data(apps, schema_editor):
    """活动已迁移至 activities app（ADR 0007）；清除旧 activity 行（反馈 feedback 保留）。

    在移除活动字段 / Vote 模型之前执行：此时 Vote 表仍在，删除 activity 申报会
    CASCADE 连带删其投票行。反馈数据不受影响。SQLite dev-only，数据清零（不可逆）。
    """
    Proposal = apps.get_model("proposals", "Proposal")
    Proposal.objects.filter(proposal_type="activity").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_delete_proposalattachment'),
    ]

    operations = [
        migrations.RunPython(delete_activity_data, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-created_at'], 'permissions': [('approve_proposal', '可审批反馈'), ('view_feedback', '可查看意见反馈/举报')], 'verbose_name': '申报', 'verbose_name_plural': '申报'},
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='expected_participants',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='location',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='planned_date',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='voting_end_at',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_type',
            field=models.CharField(choices=[('feedback', '意见反馈')], default='feedback', max_length=10, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='reject_reason',
            field=models.TextField(blank=True, default='', verbose_name='拒绝理由'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending_approval', '待社长审批'), ('approved', '已通过'), ('rejected', '已拒绝'), ('withdrawn', '已撤回')], default='pending_approval', max_length=20, verbose_name='状态'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
