# Generated by Django 6.0.5 on 2026-08-20 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0011_activity_voting_enabled'),
        ('news', '0002_create_info_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审'), ('approved', '通过'), ('rejected', '驳回'), ('removed', '下架')], default='pending', max_length=12, verbose_name='状态')),
                ('comment', models.TextField(blank=True, default='', verbose_name='评语')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication_review', to='activities.activity', verbose_name='活动')),
                ('news', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='news.news', verbose_name='新闻')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '审核',
                'verbose_name_plural': '审核',
                'ordering': ['-created_at'],
                'permissions': [('force_publish', '可免审发布'), ('moderate', '可审核内容')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('activity__isnull', True), ('news__isnull', False)), models.Q(('activity__isnull', False), ('news__isnull', True)), _connector='OR'), name='review_exactly_one_parent')],
            },
        ),
    ]
