# Generated by Django 6.0.5

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0013_questionnaire"),
        ("messaging", "0004_grant_messaging_perms"),
        ("news", "0003_remove_news_category"),
        ("reviews", "0005_review_tutorial"),
        ("tutorials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(choices=[("suggestion", "建议"), ("complaint", "投诉"), ("other", "其他")], max_length=20, verbose_name="类别")),
                ("status", models.CharField(choices=[("pending", "待处理"), ("closed", "已了结")], default="pending", max_length=12, verbose_name="状态")),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("description", models.TextField(blank=True, default="", verbose_name="详细说明")),
                ("contact", models.CharField(blank=True, default="", max_length=100, verbose_name="联系方式（选填）")),
                ("closed_at", models.DateTimeField(blank=True, null=True, verbose_name="了结时间")),
                ("close_note", models.TextField(blank=True, default="", verbose_name="了结说明")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="closed_feedbacks", to=settings.AUTH_USER_MODEL, verbose_name="了结人")),
                ("creator", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_feedbacks", to=settings.AUTH_USER_MODEL, verbose_name="创建人")),
            ],
            options={
                "verbose_name": "意见反馈",
                "verbose_name_plural": "意见反馈",
                "ordering": ["-created_at"],
                "default_permissions": ("add", "change", "delete"),
                "permissions": [("view_feedback", "可查看并了结意见反馈")],
            },
        ),
        migrations.CreateModel(
            name="ReportCase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("open", "进行中"), ("dismissed", "驳回"), ("upheld", "成立并处置")], default="open", max_length=12, verbose_name="状态")),
                ("resolved_at", models.DateTimeField(blank=True, null=True, verbose_name="处理时间")),
                ("resolution_comment", models.TextField(blank=True, default="", verbose_name="处理说明")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activity", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="report_cases", to="activities.activity", verbose_name="活动")),
                ("comment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="report_cases", to="messaging.comment", verbose_name="评论")),
                ("news", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="report_cases", to="news.news", verbose_name="新闻")),
                ("reported_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="report_cases_against", to=settings.AUTH_USER_MODEL, verbose_name="被举报用户")),
                ("resolved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resolved_report_cases", to=settings.AUTH_USER_MODEL, verbose_name="处理人")),
                ("tutorial", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="report_cases", to="tutorials.tutorial", verbose_name="教程")),
            ],
            options={
                "verbose_name": "举报案",
                "verbose_name_plural": "举报案",
                "ordering": ["-created_at"],
                "permissions": [("handle_report", "可处理举报案")],
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            models.Q(news__isnull=False, activity__isnull=True, tutorial__isnull=True, comment__isnull=True, reported_user__isnull=True)
                            | models.Q(news__isnull=True, activity__isnull=False, tutorial__isnull=True, comment__isnull=True, reported_user__isnull=True)
                            | models.Q(news__isnull=True, activity__isnull=True, tutorial__isnull=False, comment__isnull=True, reported_user__isnull=True)
                            | models.Q(news__isnull=True, activity__isnull=True, tutorial__isnull=True, comment__isnull=False, reported_user__isnull=True)
                            | models.Q(news__isnull=True, activity__isnull=True, tutorial__isnull=True, comment__isnull=True, reported_user__isnull=False)
                        ),
                        name="reportcase_exactly_one_target",
                    ),
                    models.UniqueConstraint(condition=models.Q(("news__isnull", False), ("status", "open")), fields=("news",), name="one_open_report_per_news"),
                    models.UniqueConstraint(condition=models.Q(("activity__isnull", False), ("status", "open")), fields=("activity",), name="one_open_report_per_activity"),
                    models.UniqueConstraint(condition=models.Q(("tutorial__isnull", False), ("status", "open")), fields=("tutorial",), name="one_open_report_per_tutorial"),
                    models.UniqueConstraint(condition=models.Q(("comment__isnull", False), ("status", "open")), fields=("comment",), name="one_open_report_per_comment"),
                    models.UniqueConstraint(condition=models.Q(("reported_user__isnull", False), ("status", "open")), fields=("reported_user",), name="one_open_report_per_user"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportFiling",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.TextField(verbose_name="理由")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="filings", to="reviews.reportcase", verbose_name="举报案")),
                ("reporter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="report_filings", to=settings.AUTH_USER_MODEL, verbose_name="举报人")),
            ],
            options={
                "verbose_name": "举报",
                "verbose_name_plural": "举报",
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("case", "reporter"), name="one_filing_per_reporter_per_case"),
                ],
            },
        ),
    ]
