# Generated by Django 6.0.5 on 2026-09-18 11:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_alter_activity_options'),
        ('messaging', '0001_initial_squashed_0004_grant_messaging_perms'),
        ('news', '0004_alter_news_options'),
        ('reviews', '0007_copy_proposals_to_feedback_squashed_0008_grant_feedback_and_report_to_president'),
        ('tutorials', '0004_alter_tutorial_options_alter_tutorial_cover_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'default_permissions': ('add', 'change', 'delete'), 'ordering': ['-created_at'], 'permissions': [('read_feedback', '可查看并了结意见反馈')], 'verbose_name': '意见反馈', 'verbose_name_plural': '意见反馈'},
        ),
    ]
