# Generated by Django 6.0.5 on 2026-09-25 12:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_remove_questionnaireresponse_unique_questionnaire_response_per_user_and_more'),
        ('messaging', '0007_remove_usermute_messaging_u_user_id_c1296f_idx_and_more'),
        ('news', '0006_news_draft_content_news_draft_saved_at_and_more'),
        ('reviews', '0009_alter_feedback_options_and_more'),
        ('tutorials', '0005_alter_tutorial_cover_alter_tutorial_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # UserMute 自 messaging 迁入（表名保留 messaging_usermute）：仅改状态，DDL 零执行。
        # ReportCase 约束为 Q 顺序噪音（语义等价），同样只改状态避免 SQLite 重建表。
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='UserMute',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('reason', models.TextField(blank=True, default='', verbose_name='理由')),
                        ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                        ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                        ('lifted_at', models.DateTimeField(blank=True, null=True, verbose_name='解除时间')),
                    ],
                    options={
                        'verbose_name': '禁言',
                        'verbose_name_plural': '禁言',
                        'db_table': 'messaging_usermute',
                        'ordering': ['-starts_at'],
                        'permissions': [('mute_user', '全站禁言')],
                    },
                ),
                migrations.AddField(
                    model_name='usermute',
                    name='muted_by',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_mutes', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
                ),
                migrations.AddField(
                    model_name='usermute',
                    name='user',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutes', to=settings.AUTH_USER_MODEL, verbose_name='被禁言用户'),
                ),
                migrations.AddIndex(
                    model_name='usermute',
                    index=models.Index(fields=['user', 'lifted_at', 'ends_at'], name='messaging_u_user_id_c1296f_idx'),
                ),
                migrations.RemoveConstraint(
                    model_name='reportcase',
                    name='one_open_report_per_tutorial',
                ),
                migrations.AddConstraint(
                    model_name='reportcase',
                    constraint=models.UniqueConstraint(condition=models.Q(('status', 'open'), ('tutorial__isnull', False)), fields=('tutorial',), name='one_open_report_per_tutorial'),
                ),
            ],
            database_operations=[],
        ),
    ]
