"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# 是否在跑测试（manage.py test / Django test runner）。仅据此切换「测试期才该变」的
# 面向速度与隔离的设置——绝不影响 runserver / 生产。
TESTING = "test" in sys.argv or os.environ.get("DJANGO_TESTING") == "1"

# 拉取项目根 .env（.gitignore，不入库）。本地开发放 SECRET_KEY / SMTP 授权码 /
# Turnstile secret 等运行期密钥；生产由进程环境提供，.env 缺失时 load_dotenv 安静返回。
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ── 测试期提速（仅 TESTING=True 生效，零生产影响）───────────────────────────
# 实测：默认 PBKDF2 约 374ms/次；全套 ~200 次 create_user → 光密码哈希就占
# 总时长 816s 的 ~45%。切 MD5（不可逆弱哈希）后单类测试 16.8s → 0.09s（190×）。
# 测试库数据每次清空、绝不进生产，密码强度在此无意义。
if TESTING:
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]
    # 邮件走内存后端：注册/验证/重置路径发信不触网、不阻塞、可断言 mail.outbox。
    # （防御性：本地若在 .env 配了 EMAIL_HOST_USER，否则会被切到真实 SMTP smtp.163.com。）
    EMAIL_BACKEND = "django.core.mail.backends.locmem.EmailBackend"


def _email_backend_for(host_user):
    """邮件后端选择：配了 SMTP 用户名 → 163 SMTP（SSL/465）；否则 dev 用 console。

    既有密码重置邮件自动走此后端（dev 打终端、prod SMTP），无需改密码重置代码。
    """
    if host_user:
        return "django.core.mail.backends.smtp.EmailBackend"
    return "django.core.mail.backends.console.ConsoleEmailBackend"


def _parse_allowed_hosts(raw):
    """ALLOWED_HOSTS：env 逗号分隔 → list；未配置返回 []（dev 本地由 DEBUG 兜底）。"""
    return [h.strip() for h in raw.split(",") if h.strip()] if raw else []


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# 密钥 / 调试 / 允许主机全部走环境变量（模板见 .env.example）。下列默认值仅保本地开箱即用；
# 生产务必通过 .env / 进程环境覆盖（尤其 SECRET_KEY，默认值是公开占位、不安全）。
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-8725+3f=oec+rp*g+(dq_86xa$87!1)40k9)r@zc&oyc8&db%+",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1").lower() in ("1", "true", "yes", "on")

ALLOWED_HOSTS = _parse_allowed_hosts(os.environ.get("ALLOWED_HOSTS", ""))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'common',
    'accounts',
    'about',
    'tasks',
    'messaging',
    'proposals',
    'activities',
    'exam_board',
    'news',
    'reviews',
    'tutorials',
    'recruitment',
    'attachments',
    'rest_framework_tus',
]

MIDDLEWARE = [
    # 维护旗标 run/MAINTENANCE：503 HTML，不碰 DB / session（须先于 Session/CSRF/Tus）。
    'common.middleware.MaintenanceModeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.SingleSessionMiddleware',
    # tus 可续传上传：把 Tus-* / Upload-* 请求头解析到 request 属性上。
    'rest_framework_tus.middleware.TusMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'frontend' / 'dist',
    BASE_DIR / 'static'
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]
CORS_ALLOW_CREDENTIALS = True

# ---- 邮件 / SMTP ----
# 163 邮箱 SMTP：配了 EMAIL_HOST_USER（+ EMAIL_HOST_PASSWORD 授权码）即切到 SMTP，
# 否则 dev 用 console 后端（邮件打终端，便于本地调试注册 / 重置流程）。
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_BACKEND = _email_backend_for(EMAIL_HOST_USER)
if EMAIL_HOST_USER:
    EMAIL_HOST = "smtp.163.com"
    EMAIL_PORT = 465
    EMAIL_USE_SSL = True
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

LOGIN_URL = "/login/"

# Origin of the frontend, used to build links sent to users (e.g. password-reset /
# verify-email email). Override via the FRONTEND_URL env var in production.
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000")

# Media files (公开用户上传：头像等)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# 私有媒体（身份证明等审计留底）：绝不经公开 MEDIA_URL 暴露，由带鉴权的视图服务。
# 注意：DEBUG 下 config/urls.py 会用 static(MEDIA_URL) 公开服务整个 MEDIA_ROOT，
# 故私有存储必须落在 MEDIA_ROOT 之外（见 #31 / ADR 0002）。
PRIVATE_MEDIA_ROOT = BASE_DIR / "private_media"

# ---- Cloudflare Turnstile（人机校验，自助注册用）----
# sitekey 公开（前端常量）；secret 走 .env。DEBUG 或未配 secret 时跳过校验（本地可测）。
TURNSTILE_SITE_KEY = os.environ.get("TURNSTILE_SITE_KEY", "")
TURNSTILE_SECRET_KEY = os.environ.get("TURNSTILE_SECRET_KEY", "")

# GitHub Release auto-update (spawned by start.sh next to Gunicorn). Token is the secret;
# repo is optional infra. Window / poll knobs live in SiteSettings (ADR-0010).
UPDATE_GITHUB_TOKEN = os.environ.get("UPDATE_GITHUB_TOKEN", "")
UPDATE_GITHUB_REPO = (
    os.environ.get("UPDATE_GITHUB_REPO", "nanhui-no1-media/Backend")
    or "nanhui-no1-media/Backend"
)

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Operational throttle rates live in common.SiteSettings (get_policy()),
    # not here. Empty dict so DRF has a well-formed setting; the three scopes
    # override get_rate() and do not read this map.
    'DEFAULT_THROTTLE_RATES': {},
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# drf-tus（tus 可续传上传）。图/视频走 tus 通路；详见 ADR 0004（#21）。
# Live cap is common.SiteSettings.tus_media_max_bytes (get_policy()); this
# value is the library fallback and matches the SiteSettings field default.
REST_FRAMEWORK_TUS = {
    "MAX_FILE_SIZE": 500 * 1024 * 1024,  # library fallback; viewset reads get_policy()
    "TUS_UPLOAD_DESTINATION": "tus_uploaded",  # drf-tus 落地目录（相对 MEDIA_ROOT）
    "UPLOAD_MODEL": "attachments.TusUpload",  # 自定义模型，补 user 外键
    # UPLOAD_DIR（临时分片）默认 BASE_DIR/tmp/uploads；UPLOAD_EXPIRES 默认 1 天。
}
