# Generated by Django 6.0.5 on 2026-08-27 12:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def delete_non_private_conversations(apps, schema_editor):
    """Drop task/proposal sessions (and cascaded messages) before slimming Conversation."""
    Conversation = apps.get_model("messaging", "Conversation")
    Conversation.objects.exclude(conversation_type="private").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_questionnaire'),
        ('messaging', '0001_initial'),
        ('news', '0003_remove_news_category'),
        ('tasks', '0002_delete_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(delete_non_private_conversations, migrations.RunPython.noop),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='正文')),
                ('link', models.CharField(blank=True, default='', max_length=500, verbose_name='链接')),
                ('starts_at', models.DateTimeField(verbose_name='开始时间')),
                ('ends_at', models.DateTimeField(verbose_name='结束时间')),
                ('priority', models.IntegerField(default=0, help_text='数值越大越优先；相同则较新者胜出。', verbose_name='优先级')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '横幅公告',
                'verbose_name_plural': '横幅公告',
                'ordering': ['-priority', '-created_at'],
                'permissions': [('manage_announcement', '管理横幅公告')],
            },
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='conversation_type',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='task',
        ),
        migrations.AddField(
            model_name='message',
            name='retracted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='撤回时间'),
        ),
        migrations.CreateModel(
            name='CommentThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', '开放'), ('muted', '禁言'), ('closed', '关闭')], default='open', max_length=10, verbose_name='状态')),
                ('activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_thread', to='activities.activity', verbose_name='活动')),
                ('news', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_thread', to='news.news', verbose_name='新闻')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_thread', to='tasks.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '评论区',
                'verbose_name_plural': '评论区',
                'permissions': [('manage_comment_thread', '评论区协管')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('retracted_at', models.DateTimeField(blank=True, null=True, verbose_name='撤回时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_comments', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_comments', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='messaging.comment', verbose_name='父评论')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='messaging.commentthread', verbose_name='评论区')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('comment', '评论'), ('review', '审核'), ('discipline', '纪律')], max_length=20, verbose_name='类别')),
                ('event', models.CharField(max_length=64, verbose_name='事件')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='载荷')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='', verbose_name='理由')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('lifted_at', models.DateTimeField(blank=True, null=True, verbose_name='解除时间')),
                ('muted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_mutes', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutes', to=settings.AUTH_USER_MODEL, verbose_name='被禁言用户')),
            ],
            options={
                'verbose_name': '禁言',
                'verbose_name_plural': '禁言',
                'ordering': ['-starts_at'],
                'permissions': [('mute_user', '全站禁言')],
            },
        ),
        migrations.AddConstraint(
            model_name='commentthread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activity__isnull', True), ('news__isnull', False), ('task__isnull', True)), models.Q(('activity__isnull', False), ('news__isnull', True), ('task__isnull', True)), models.Q(('activity__isnull', True), ('news__isnull', True), ('task__isnull', False)), _connector='OR'), name='commentthread_exactly_one_parent', violation_error_message='评论区必须且只能挂在一个宿主（新闻/活动/任务）上。'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['thread', 'parent', 'created_at'], name='messaging_c_thread__2648d9_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='messaging_n_recipie_0f301b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read_at'], name='messaging_n_recipie_736adb_idx'),
        ),
        migrations.AddIndex(
            model_name='usermute',
            index=models.Index(fields=['user', 'lifted_at', 'ends_at'], name='messaging_u_user_id_c1296f_idx'),
        ),
    ]
