# Generated by Django 6.0.5 on 2026-07-05 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='proposals.proposal', verbose_name='关联申报'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('task', '任务讨论'), ('private', '私人对话'), ('proposal', '申报讨论')], max_length=10, verbose_name='类型'),
        ),
    ]
