# Generated by Django 6.0.5 on 2026-09-25 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial_squashed_0004_grant_messaging_perms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('review', '审核'), ('activity', '活动'), ('comment', '评论'), ('dm', '私信'), ('announcement', '广播'), ('discipline', '纪律')], max_length=20, verbose_name='类别'),
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_key', models.CharField(max_length=32, verbose_name='通道')),
                ('status', models.CharField(choices=[('pending', '待投递'), ('sent', '已送达'), ('failed', '失败')], default='pending', max_length=12, verbose_name='状态')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='尝试次数')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='最后错误')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='下次重试时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='messaging.notification', verbose_name='通知')),
            ],
            options={
                'verbose_name': '通知投递',
                'verbose_name_plural': '通知投递',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='messaging_n_status_282162_idx'), models.Index(fields=['channel_key', 'status'], name='messaging_n_channel_3461d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=32, verbose_name='源')),
                ('channel_key', models.CharField(max_length=32, verbose_name='通道')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '通知订阅',
                'verbose_name_plural': '通知订阅',
                'unique_together': {('user', 'source_key', 'channel_key')},
            },
        ),
    ]
