# Generated by Django 6.0.5 on 2026-09-25 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_migrate_email_prefs_to_subscriptions'),
    ]

    operations = [
        # UserMute 迁往 reviews（表名保留 messaging_usermute，数据零迁移）：
        # 仅改状态，数据库层不动（表/索引继续由 reviews 侧模型使用）。
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='usermute',
                    name='messaging_u_user_id_c1296f_idx',
                ),
                migrations.DeleteModel(
                    name='UserMute',
                ),
            ],
            database_operations=[],
        ),
    ]
