# Generated by Django 6.0.5 on 2026-05-24 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='group',
        ),
        migrations.RemoveField(
            model_name='department',
            name='head',
        ),
        migrations.RemoveField(
            model_name='task',
            name='department',
        ),
        migrations.CreateModel(
            name='TaskClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='状态')),
                ('reason', models.TextField(blank=True, verbose_name='申请理由')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请者')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='tasks.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '认领请求',
                'verbose_name_plural': '认领请求',
                'ordering': ['-created_at'],
                'unique_together': {('task', 'claimant')},
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
