# Generated by Django 6.0.5 on 2026-05-31 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_department_group_remove_department_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
    ]
