# Generated by Django 6.0.5 on 2026-06-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_due_date_remove_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reject_reason',
            field=models.TextField(blank=True, default='', verbose_name='打回理由'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('reviewing', '待验收'), ('review', '审核中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
