# Generated by Django 6.0.5 on 2026-07-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_reject_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'permissions': [('manage_tags', '可管理标签')], 'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'permissions': [('manage_tasks', '可管理/审批任意任务'), ('assign_task', '可直接指派任务')], 'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
    ]
