# Generated by Django 6.0.5 on 2026-07-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='关于我们', max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='正文（HTML）')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '关于页',
                'verbose_name_plural': '关于页',
            },
        ),
    ]
