# Generated by Django 6.0.5

from django.db import migrations, models


def about_document_path(instance, filename):
    ext = filename.rsplit(".", 1)[-1].lower() if "." in filename else "bin"
    return f"about_documents/{instance.key}.{ext}"


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_seed_about_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="advisor",
            field=models.CharField(default="信息组", max_length=80, verbose_name="指导"),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="founded",
            field=models.CharField(default="2026.03", max_length=40, verbose_name="成立"),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="intro",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="简介"),
        ),
        migrations.CreateModel(
            name="AboutBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(max_length=40, unique=True, verbose_name="键")),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(blank=True, default="", verbose_name="正文（HTML）")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="排序")),
                ("panorama_url", models.URLField(blank=True, default="", verbose_name="校园全景图外链")),
                ("document", models.FileField(blank=True, upload_to=about_document_path, verbose_name="文档附件")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "关于区块",
                "verbose_name_plural": "关于区块",
                "ordering": ["order", "id"],
            },
        ),
    ]
