# Generated by Django 6.0.5 on 2026-09-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_grant_change_to_info_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'permissions': [('manage_aboutpage', '可编辑关于页')], 'verbose_name': '关于页', 'verbose_name_plural': '关于页'},
        ),
    ]
