# Generated by Django 6.0.5 on 2026-09-25 15:39

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_aboutpage_options_alter_aboutblock_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutblock',
            name='document',
            field=models.FileField(blank=True, upload_to=about.models.about_document_path, verbose_name='文档附件'),
        ),
    ]
