# Generated by Django 6.0.5

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid
import os


def tutorial_file_path(instance, filename):
    ext = os.path.splitext(filename)[1]
    return f"tutorials/{uuid.uuid4().hex}{ext}"


def tutorial_cover_path(instance, filename):
    ext = os.path.splitext(filename)[1]
    return f"tutorial_covers/{uuid.uuid4().hex}{ext}"


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorialTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=40, unique=True, verbose_name="名称")),
                ("kind", models.CharField(choices=[("tool", "使用工具"), ("scene", "使用场景")], max_length=12, verbose_name="类别")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="排序")),
            ],
            options={"ordering": ["kind", "order", "id"], "verbose_name": "教程标签", "verbose_name_plural": "教程标签"},
        ),
        migrations.CreateModel(
            name="Tutorial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("description", models.TextField(blank=True, default="", verbose_name="描述")),
                ("file", models.FileField(upload_to=tutorial_file_path, verbose_name="文件")),
                ("file_type", models.CharField(choices=[("video", "视频"), ("document", "文档")], max_length=12, verbose_name="文件类型")),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                ("file_size", models.BigIntegerField(default=0, verbose_name="文件大小")),
                ("cover", models.ImageField(blank=True, upload_to=tutorial_cover_path, verbose_name="封面")),
                ("views", models.PositiveIntegerField(default=0, verbose_name="播放量")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uploader", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tutorials", to=settings.AUTH_USER_MODEL, verbose_name="上传者")),
                ("tags", models.ManyToManyField(blank=True, related_name="tutorials", to="tutorials.tutorialtag", verbose_name="标签")),
            ],
            options={"ordering": ["-created_at"], "verbose_name": "教程", "verbose_name_plural": "教程"},
        ),
        migrations.CreateModel(
            name="TutorialView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reader_key", models.CharField(max_length=80, verbose_name="读者标识")),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                ("tutorial", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="view_records", to="tutorials.tutorial", verbose_name="教程")),
            ],
            options={"verbose_name": "播放记录", "unique_together": {("tutorial", "reader_key")}},
        ),
        migrations.CreateModel(
            name="TutorialFavorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tutorial", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="favorites", to="tutorials.tutorial", verbose_name="教程")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tutorial_favorites", to=settings.AUTH_USER_MODEL, verbose_name="用户")),
            ],
            options={"verbose_name": "教程收藏", "unique_together": {("tutorial", "user")}},
        ),
    ]
