# Generated by Django 6.0.5 on 2026-09-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_remove_tutorial_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['-created_at'], 'permissions': [('manage_tutorials', '可管理教程')], 'verbose_name': '教程', 'verbose_name_plural': '教程'},
        ),
    ]
