# Generated by Django 6.0.5 on 2026-09-25 12:57

import tutorials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_alter_tutorial_options_alter_tutorial_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='cover',
            field=models.ImageField(blank=True, upload_to=tutorials.models.tutorial_cover_path, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='file',
            field=models.FileField(upload_to=tutorials.models.tutorial_file_path, verbose_name='文件'),
        ),
    ]
