# Generated by Django 6.0.5 on 2026-07-23 09:24

import attachments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=attachments.models.attachment_upload_path, verbose_name='文件')),
                ('file_type', models.CharField(choices=[('image', '图片'), ('video', '视频'), ('document', '文档'), ('archive', '压缩包'), ('other', '其他')], max_length=20, verbose_name='文件类型')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='proposals.proposal', verbose_name='申报')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task', verbose_name='任务')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'ordering': ['-uploaded_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('proposal__isnull', False), ('task__isnull', True)), models.Q(('proposal__isnull', True), ('task__isnull', False)), _connector='OR'), name='attachment_exactly_one_parent', violation_error_message='附件必须且只能挂在一个父级（任务或申报）上。')],
            },
        ),
    ]
