# Generated by Django 6.0.5 on 2026-07-30 09:19

import collections
import django.db.models.deletion
import django_fsm
import jsonfield.fields
import rest_framework_tus.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TusUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='GUID')),
                ('state', django_fsm.FSMField(default='initial', max_length=50)),
                ('upload_offset', models.BigIntegerField(default=0)),
                ('upload_length', models.BigIntegerField(default=-1)),
                ('upload_metadata', jsonfield.fields.JSONField(load_kwargs={'object_pairs_hook': collections.OrderedDict})),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('temporary_file_path', models.CharField(max_length=4096, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, max_length=255, null=True, upload_to=rest_framework_tus.models.custom_upload_path, verbose_name='完成文件')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tus_uploads', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': 'tus 上传',
                'verbose_name_plural': 'tus 上传',
            },
        ),
    ]
