# Generated by Django 6.0.5 on 2026-07-30 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_tusupload'),
        ('news', '0002_create_info_group'),
        ('proposals', '0002_delete_proposalattachment'),
        ('tasks', '0002_delete_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attachment',
            name='attachment_exactly_one_parent',
        ),
        migrations.AddField(
            model_name='attachment',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='news.news', verbose_name='新闻'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('news__isnull', True), ('proposal__isnull', True), ('task__isnull', False)), models.Q(('news__isnull', True), ('proposal__isnull', False), ('task__isnull', True)), models.Q(('news__isnull', False), ('proposal__isnull', True), ('task__isnull', True)), _connector='OR'), name='attachment_exactly_one_parent', violation_error_message='附件必须且只能挂在一个父级（任务/申报/新闻）上。'),
        ),
    ]
