# Generated by Django 6.0.5 on 2026-08-07 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_activity_type_exhibit_exhibitrating'),
        ('attachments', '0004_remove_attachment_attachment_exactly_one_parent_and_more'),
        ('news', '0002_create_info_group'),
        ('proposals', '0003_alter_proposal_options_remove_proposal_activity_type_and_more'),
        ('tasks', '0002_delete_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attachment',
            name='attachment_exactly_one_parent',
        ),
        migrations.AddField(
            model_name='attachment',
            name='exhibit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='activities.exhibit', verbose_name='展品'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('exhibit__isnull', True), ('news__isnull', True), ('proposal__isnull', True), ('submission__isnull', True), ('task__isnull', False)), models.Q(('exhibit__isnull', True), ('news__isnull', True), ('proposal__isnull', False), ('submission__isnull', True), ('task__isnull', True)), models.Q(('exhibit__isnull', True), ('news__isnull', False), ('proposal__isnull', True), ('submission__isnull', True), ('task__isnull', True)), models.Q(('exhibit__isnull', True), ('news__isnull', True), ('proposal__isnull', True), ('submission__isnull', False), ('task__isnull', True)), models.Q(('exhibit__isnull', False), ('news__isnull', True), ('proposal__isnull', True), ('submission__isnull', True), ('task__isnull', True)), _connector='OR'), name='attachment_exactly_one_parent', violation_error_message='附件必须且只能挂在一个父级（任务/申报/新闻/作品/展品）上。'),
        ),
    ]
