# Generated by Django 6.0.5 on 2026-07-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.CharField(blank=True, max_length=10)),
                ('exam_title', models.CharField(blank=True, max_length=50)),
                ('exam_list', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
