# Generated by Django 6.0.5

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards(apps, schema_editor):
    ExamData = apps.get_model("exam_board", "ExamData")
    # 旧 CharField 空日期无法转 DateField：清掉空行，合法 YYYY-MM-DD 留给 AlterField。
    ExamData.objects.filter(exam_date="").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("exam_board", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="examdata",
            options={"ordering": ["-exam_date", "-id"], "verbose_name": "考试", "verbose_name_plural": "考试"},
        ),
        migrations.AddField(
            model_name="examdata",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="examdata",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="examdata",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exam_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="写入人",
            ),
        ),
        migrations.AlterField(
            model_name="examdata",
            name="exam_date",
            field=models.DateField(verbose_name="考试日期"),
        ),
        migrations.AlterField(
            model_name="examdata",
            name="exam_title",
            field=models.CharField(max_length=50, verbose_name="考试标题"),
        ),
        migrations.AlterField(
            model_name="examdata",
            name="exam_list",
            field=models.CharField(max_length=255, verbose_name="科目列表"),
        ),
    ]
