# Generated by Django 6.0.5 on 2026-05-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdata',
            name='exam_date',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
