# Generated by Django 6.0.5 on 2026-09-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_board', '0006_examerrata_exam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-id'], 'permissions': [('manage_exams', '可管理考试看板')], 'verbose_name': '考试', 'verbose_name_plural': '考试'},
        ),
    ]
